service: awsnodetraining-mike-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  timeout: 15
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: 'awsnodejstraining'
  memorySize: 256 # mb
  environment:
    REIMBURSEMENT_TABLE: flexben_group3
    SECRET_KEY: )x2f-l-opsnd)w!!z2m7ykvony99pt@6@6m+=q2uk3%w8*7$ow
    CLEAR_SECRET_KEY: clear
    ALGORITHM: HS256
    ISSUER: FLEXBENAPP_COM
    EXPIRY: 15m
    MIN_REIMBURSABLE_AMOUNT: 500
    TAX_RATE: 0.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - arn:aws:dynamodb:ap-southeast-1:702954692849:table/flexben_group3


plugins:
  - serverless-offline
  - serverless-express

custom:
  serverless-offline:
    httpPort: 8080

functions:
  api:
    role: arn:aws:iam::702954692849:role/awsnodetraining-dev-role
    handler: handler.handler
    events:
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - PoolId
              - TenantId
              - isEso
              - userId
            allowCredentials: true   

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
